INSERT INTO user (id, first_name, last_name) VALUES (1, 'FUser 1', 'LUser 1');
INSERT INTO user (id, first_name, last_name) VALUES (2, 'FUser 2', 'LUser 2');
INSERT INTO user (id, first_name, last_name) VALUES (3, 'FUser 3', 'LUser 3');
INSERT INTO user (id, first_name, last_name) VALUES (4, 'FUser 4', 'LUser 4');

INSERT INTO article (id, title, type, author) VALUES (1, 'Title 1', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (2, 'Title 2', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (3, 'Title 3', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (4, 'Title 4', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (5, 'Title 5', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (6, 'Title 6', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (7, 'Title 7', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (8, 'Title 8', 'NEW', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (9, 'Title 9', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (10, 'Title 10', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (11, 'Title 11', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (12, 'Title 12', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (13, 'Title 13', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (14, 'Title 14', 'CLASSIC', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (15, 'Title 15', 'STANDARD', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (16, 'Title 16', 'STANDARD', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (17, 'Title 17', 'STANDARD', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (18, 'Title 18', 'STANDARD', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (19, 'Title 19', 'STANDARD', 'xyz');
INSERT INTO article (id, title, type, author) VALUES (20, 'Title 20', 'STANDARD', 'xyz');